/* SDL2 configured for GLaDOS, written by hand.
 *
 * SDL's Linux config is normally generated by cmake, and there is no cmake on
 * this host. But SDL already ships several *hand-written* configs for Linux
 * targets that never had one either -- `SDL_config_pandora.h` is one -- so
 * this is that arrangement with a different set of drivers, not a new idea.
 *
 * **Under-declaring a HAVE_ is safe and over-declaring is not.** SDL falls
 * back to its own implementation of anything it is not told the platform has,
 * so a missing define costs a slightly larger library; a define for something
 * glibc does not actually export is a link error at best and a wrong answer at
 * worst. The list below is the Pandora config's, which is a real Linux one,
 * plus what this machine adds.
 *
 * Four drivers and each is a decision:
 *
 * - **Video is `glados` and `dummy`, and nothing else.** X11 needs a server,
 *   Wayland needs a compositor, KMSDRM needs `/dev/dri` and EGL. This machine
 *   has a framebuffer, so the driver writes to it.
 * - **Input is `SDL_INPUT_LINUXEV`**, which is evdev, which is exactly what
 *   `/dev/input/event0` and `event1` are. SDL's own code, unmodified, reading
 *   the devices this kernel grew last.
 * - **Audio is dummy, and the reason is a missing driver rather than missing
 *   hardware.** `dev::registry` carries the row already: an HD Audio
 *   controller, class 04:03, `Support::Known("no audio stack")` -- recognised,
 *   with nothing behind it. That distinction is the whole point of the
 *   registry and it is worth keeping straight here, because "no sound
 *   hardware" reads as impossible where "no driver yet" reads as a job.
 *   Intel HDA is published, needs no signed blob, and QEMU emulates
 *   `intel-hda`, so unlike the wireless dongle it could be exercised from
 *   this desk.
 * - **Threads are pthreads**, which is `clone` and `futex`, which arrived a
 *   few commits ago and are the reason this is possible at all.
 */

#ifndef SDL_config_glados_h_
#define SDL_config_glados_h_
#define SDL_config_h_

#include "SDL_platform.h"

#define SIZEOF_VOIDP 8
#define SDL_BYTEORDER 1234

#define STDC_HEADERS 1
#define HAVE_ALLOCA_H 1
#define HAVE_CTYPE_H 1
#define HAVE_FLOAT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIMITS_H 1
#define HAVE_MALLOC_H 1
#define HAVE_MATH_H 1
#define HAVE_MEMORY_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_STDARG_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_WCHAR_H 1

#define HAVE_LIBC 1
#define HAVE_DLOPEN 1
#define HAVE_MALLOC 1
#define HAVE_CALLOC 1
#define HAVE_REALLOC 1
#define HAVE_FREE 1
#define HAVE_ALLOCA 1
#define HAVE_GETENV 1
#define HAVE_SETENV 1
#define HAVE_PUTENV 1
#define HAVE_UNSETENV 1
#define HAVE_QSORT 1
#define HAVE_BSEARCH 1
#define HAVE_ABS 1
#define HAVE_BCOPY 1
#define HAVE_MEMSET 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMCMP 1
#define HAVE_WCSLEN 1
#define HAVE_WCSCMP 1
#define HAVE_STRLEN 1
#define HAVE_STRCHR 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOL 1
#define HAVE_STRTOUL 1
#define HAVE_STRTOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRTOD 1
#define HAVE_ATOI 1
#define HAVE_ATOF 1
#define HAVE_STRCMP 1
#define HAVE_STRNCMP 1
#define HAVE_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_VSSCANF 1
#define HAVE_VSNPRINTF 1
#define HAVE_M_PI 1
#define HAVE_ACOS 1
#define HAVE_ASIN 1
#define HAVE_ATAN 1
#define HAVE_ATAN2 1
#define HAVE_CEIL 1
#define HAVE_COPYSIGN 1
#define HAVE_COS 1
#define HAVE_COSF 1
#define HAVE_EXP 1
#define HAVE_FABS 1
#define HAVE_FLOOR 1
#define HAVE_FMOD 1
#define HAVE_LOG 1
#define HAVE_LOG10 1
#define HAVE_LROUND 1
#define HAVE_LROUNDF 1
#define HAVE_POW 1
#define HAVE_ROUND 1
#define HAVE_ROUNDF 1
#define HAVE_SCALBN 1
#define HAVE_SIN 1
#define HAVE_SINF 1
#define HAVE_SQRT 1
#define HAVE_SQRTF 1
#define HAVE_TAN 1
#define HAVE_TANF 1
#define HAVE_TRUNC 1
#define HAVE_TRUNCF 1
#define HAVE_SIGACTION 1
#define HAVE_SETJMP 1
#define HAVE_NANOSLEEP 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_GETPAGESIZE 1
#define HAVE_MPROTECT 1
#define HAVE_ICONV 1
#define HAVE_ICONV_H 1
#define HAVE_SYSCONF 1

/* Video: this machine's framebuffer, plus the dummy so a program that asks
 * for no display still starts. `SDL_VIDEODRIVER=glados` or nothing at all,
 * since the list below is tried in order. */
#define SDL_VIDEO_DRIVER_GLADOS 1
#define SDL_VIDEO_DRIVER_DUMMY 1
#define SDL_VIDEO_RENDER_SW 1

/* `linux/input.h`, which zig ships kernel headers for. It gates more than it
 * looks: `SDL_evdev_capabilities.h` puts the device-class constants *and* the
 * NBITS/test_bit macros behind it, so without this the evdev reader compiles
 * to a wall of undeclared identifiers that read like a missing library. */
#define HAVE_LINUX_INPUT_H 1

/* evdev, which is SDL's own unmodified reader of the devices this kernel
 * grew for exactly this. */
#define SDL_INPUT_LINUXEV 1

#define SDL_AUDIO_DRIVER_DUMMY 1
#define SDL_JOYSTICK_DUMMY 1
#define SDL_HAPTIC_DUMMY 1
#define SDL_SENSOR_DUMMY 1
#define SDL_POWER_DISABLED 1
#define SDL_HIDAPI_DISABLED 1
#define SDL_LOADSO_DLOPEN 1
#define SDL_THREAD_PTHREAD 1
#define SDL_THREAD_PTHREAD_RECURSIVE_MUTEX 1
#define SDL_TIMER_UNIX 1
#define SDL_FILESYSTEM_UNIX 1
#define SDL_MISC_DUMMY 1
#define SDL_LOCALE_DUMMY 1

#endif /* SDL_config_glados_h_ */
