//! Executable buffers, and knowing where a fault happened in one.
//!
//! Every page in this kernel is `PRESENT | WRITABLE` and executable -- there
//! is no NX constant in `mem::paging` and EFER.NXE is never enabled -- so a
//! page-aligned heap allocation is already a place code can run from, with no
//! page-table work at all. That is convenient and it is the reason this module
//! is careful about everything else: there is nothing between a wrong byte and
//! executing it.
//!
//! Three things are missing from the substrate without this file, and each was
//! found by reading rather than invented as a precaution:
//!
//! - **Nothing serialises.** There is no `wbinvd`, `clflush`, `mfence` or
//!   `cpuid`-as-barrier anywhere in the tree, so nothing stood between writing
//!   bytes and fetching them as instructions.
//! - **`fault()` printed a garbage RVA.** It reports `rip - IMAGE_BASE`
//!   whenever the base is known, with no check that `rip` is in the image at
//!   all. For heap-resident code that is a large number that looks exactly
//!   like a real offset into the binary, and a disassembly of the build tree
//!   will happily resolve it to an unrelated function.
//! - **The ABI is a trap on this target.** `extern "C"` on
//!   `x86_64-unknown-uefi` is Microsoft x64, not System V. `task.rs` records
//!   what happened when that was got wrong: rsp landed inside the framebuffer
//!   aperture and `ret` popped a black pixel into rip. So the calling
//!   convention is declared once, here, as a type -- no call site gets to
//!   spell it.
//!
//! There is no fault recovery in this kernel. Every IDT vector but `#BP` is
//! `-> !`: print registers, `cli; hlt`. A bad jump is an unrecoverable halt,
//! which is why the registry has to exist before the first generated byte
//! runs. It does not prevent the halt. It makes the one diagnostic that
//! survives say something true.

use core::sync::atomic::{AtomicU64, Ordering};

/// The calling convention every compiled function uses.
///
/// Declared once so no call site can spell it, and `sysv64` explicitly for
/// the reason `task.rs` documents: `extern "C"` here is Microsoft x64, which
/// passes the first integer argument in rcx rather than rdi. Both conventions
/// agree on a function taking nothing and returning in rax, so a stub that
/// takes no arguments would pass either way and prove neither. The selftest
/// therefore passes one and checks it arrived.
pub type Compiled = unsafe extern "sysv64" fn(u64) -> u64;

/// How many generated ranges can be registered at once.
///
/// Small on purpose. This is read from a fault handler, so it is a fixed
/// array of atomics rather than anything that allocates or borrows, and a
/// linear scan of eight is nothing next to the fault it is reporting.
const MAX_RANGES: usize = 8;

#[allow(clippy::declare_interior_mutable_const)]
const EMPTY: AtomicU64 = AtomicU64::new(0);

static START: [AtomicU64; MAX_RANGES] = [EMPTY; MAX_RANGES];
static LEN: [AtomicU64; MAX_RANGES] = [EMPTY; MAX_RANGES];
/// The first eight bytes of whatever content hash names the program this code
/// was generated for. Enough to find it in the namespace, and a `u64` so the
/// fault path reads one atomic instead of four.
static TAG: [AtomicU64; MAX_RANGES] = [EMPTY; MAX_RANGES];

/// Claim a slot for a range of generated code. `None` if every slot is taken.
///
/// A zero length is refused rather than stored: an empty range can never
/// contain an rip, so a slot holding one is a slot that can only mislead the
/// next reader into thinking something is registered.
pub fn register(start: u64, len: u64, tag: u64) -> Option<usize> {
    if start == 0 || len == 0 {
        return None;
    }
    for i in 0..MAX_RANGES {
        if LEN[i].load(Ordering::Relaxed) == 0 {
            START[i].store(start, Ordering::Relaxed);
            TAG[i].store(tag, Ordering::Relaxed);
            // Written last, because it is what `lookup` tests. A reader that
            // saw the length before the start would read a range that is
            // half described.
            LEN[i].store(len, Ordering::Relaxed);
            return Some(i);
        }
    }
    None
}

/// Release a slot. Cleared length first, for the reason `register` sets it
/// last.
pub fn unregister(slot: usize) {
    if slot < MAX_RANGES {
        LEN[slot].store(0, Ordering::Relaxed);
        START[slot].store(0, Ordering::Relaxed);
        TAG[slot].store(0, Ordering::Relaxed);
    }
}

/// Which generated range holds this address, and how far into it.
pub fn lookup(rip: u64) -> Option<(u64, u64)> {
    for i in 0..MAX_RANGES {
        let len = LEN[i].load(Ordering::Relaxed);
        if len == 0 {
            continue;
        }
        let start = START[i].load(Ordering::Relaxed);
        if rip >= start && rip - start < len {
            return Some((TAG[i].load(Ordering::Relaxed), rip - start));
        }
    }
    None
}

/// What an instruction pointer is inside, for the fault reporter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Where {
    /// Inside a registered range of generated code, at this offset.
    Generated { tag: u64, off: u64 },
    /// Inside the kernel image. The offset resolves in a disassembly of the
    /// binary in the build tree.
    Image(u64),
    /// An offset from the image base that nothing checked, because the
    /// image's extent was never learned -- the `LoadedImage` protocol was
    /// unavailable and the base came from scanning for an MZ header. Printed
    /// because it is still the best guess available, labelled because it is a
    /// guess.
    Unverified(u64),
    /// In neither, so there is no offset worth printing. This is the case
    /// that did not exist before: a wild rip used to be reported as an RVA
    /// with the same confidence as a real one.
    Elsewhere,
}

/// Decide what an rip is inside. Pure, so every case is asserted at boot
/// rather than waiting for a fault to find out.
///
/// Generated code is checked first. A range handed out by `Exec` is heap
/// memory and cannot overlap the loaded image, so the order is not a
/// tie-break -- it is asking the specific question before the general one.
pub fn locate(rip: u64, base: u64, size: u64, generated: Option<(u64, u64)>) -> Where {
    if let Some((tag, off)) = generated {
        return Where::Generated { tag, off };
    }
    if base == 0 {
        return Where::Elsewhere;
    }
    if size == 0 {
        return Where::Unverified(rip.wrapping_sub(base));
    }
    if rip >= base && rip - base < size {
        return Where::Image(rip - base);
    }
    Where::Elsewhere
}

/// A page-aligned buffer that code can be written into and then run.
///
/// Allocation, the barrier and the registration are one object because the
/// order between them is the whole point and a caller doing it by hand would
/// get one turn to get it right.
pub struct Exec {
    ptr: *mut u8,
    /// The allocation, a whole number of pages.
    size: usize,
    used: usize,
    slot: Option<usize>,
}

impl Exec {
    /// Round up to whole pages and take them from the ordinary heap.
    ///
    /// Page alignment is not for permissions -- every page is already
    /// executable -- it is so a range never shares a page with something else
    /// that might later want different treatment, and so the address is one a
    /// human can recognise in a fault report.
    pub fn new(bytes: usize) -> Option<Exec> {
        use alloc::alloc::{alloc_zeroed, Layout};
        let size = bytes.max(1).div_ceil(4096) * 4096;
        let layout = Layout::from_size_align(size, 4096).ok()?;
        let ptr = unsafe { alloc_zeroed(layout) };
        if ptr.is_null() {
            return None;
        }
        Some(Exec { ptr, size, used: 0, slot: None })
    }

    /// Append bytes. False if they would not fit, having written nothing.
    pub fn push(&mut self, bytes: &[u8]) -> bool {
        if self.used + bytes.len() > self.size {
            return false;
        }
        unsafe {
            core::ptr::copy_nonoverlapping(bytes.as_ptr(), self.ptr.add(self.used), bytes.len());
        }
        self.used += bytes.len();
        true
    }

    pub fn addr(&self) -> u64 {
        self.ptr as u64
    }

    pub fn len(&self) -> usize {
        self.used
    }

    pub fn is_empty(&self) -> bool {
        self.used == 0
    }

    /// Serialise, then claim a registry slot. Nothing may be executed before
    /// this returns true.
    ///
    /// The order is the reason this is one call. Serialising after
    /// registering would leave a window where the range is advertised as
    /// runnable and the processor may still hold a stale prefetch of it;
    /// registering after the first call would mean the one fault most likely
    /// to happen -- the first -- is the one with no range to name it.
    pub fn arm(&mut self, tag: u64) -> bool {
        if self.used == 0 || self.slot.is_some() {
            return false;
        }
        super::serialize();
        self.slot = register(self.addr(), self.used as u64, tag);
        self.slot.is_some()
    }

    /// The entry point, once armed.
    ///
    /// # Safety
    ///
    /// The bytes must be a valid function of exactly this signature. There is
    /// no verification here and there could not be one: this kernel has no
    /// fault recovery, so the check for "are these bytes a function" is
    /// executing them, and the answer to "no" is a halted machine.
    pub unsafe fn entry(&self) -> Option<Compiled> {
        if self.slot.is_none() {
            return None;
        }
        Some(unsafe { core::mem::transmute::<*mut u8, Compiled>(self.ptr) })
    }
}

impl Drop for Exec {
    fn drop(&mut self) {
        use alloc::alloc::{dealloc, Layout};
        if let Some(s) = self.slot.take() {
            unregister(s);
        }
        if let Ok(layout) = Layout::from_size_align(self.size, 4096) {
            unsafe { dealloc(self.ptr, layout) };
        }
    }
}

/// The substrate, exercised end to end without a code generator.
///
/// This runs machine code from the heap, which is the thing the rest of Phase
/// F depends on and which nothing in this tree had ever done. It is
/// hand-written and six bytes long, so "is the code generator correct" is not
/// one of the questions being asked -- what is being asked is whether emit,
/// serialise, register and call work at all, and whether the calling
/// convention is the one that was declared.
pub fn selftest() -> bool {
    use crate::kprintln;
    let mut ok = true;
    let mut claim = |good: bool, what: &str| {
        kprintln!("  {}   {}", if good { "ok " } else { "FAIL" }, what);
        ok &= good;
    };

    // `locate` decides what a fault reporter prints, so every state it has is
    // asserted here instead of waiting for a fault to disagree.
    claim(
        locate(0x1000, 0, 0, None) == Where::Elsewhere,
        "with no image base, nothing is claimed",
    );
    claim(
        locate(0x1040, 0x1000, 0x2000, None) == Where::Image(0x40),
        "an rip inside the image is an offset into it",
    );
    claim(
        locate(0x9000, 0x1000, 0x2000, None) == Where::Elsewhere,
        "and an rip outside it is not, which is the bug this fixes",
    );
    claim(
        locate(0x9000, 0x1000, 0, None) == Where::Unverified(0x8000),
        "with the extent unknown the offset is printed and labelled",
    );
    claim(
        locate(0x9000, 0x1000, 0x2000, Some((7, 3))) == Where::Generated { tag: 7, off: 3 },
        "generated code is named before the image is consulted",
    );

    // f(x) = 2x, in System V: the argument arrives in rdi and the answer
    // leaves in rax. Under Microsoft x64 -- which is what `extern "C"` means
    // on this target -- the argument would be in rcx and rdi would hold
    // whatever the caller last left there, so this is the claim that catches
    // the convention being got wrong.
    //
    //   48 89 f8   mov rax, rdi
    //   48 01 c0   add rax, rax
    //   c3         ret
    const DOUBLE: [u8; 7] = [0x48, 0x89, 0xf8, 0x48, 0x01, 0xc0, 0xc3];

    let Some(mut buf) = Exec::new(DOUBLE.len()) else {
        claim(false, "a page-aligned executable buffer could be taken");
        return false;
    };
    claim(buf.addr() % 4096 == 0, "a code buffer is page aligned");
    claim(buf.push(&DOUBLE), "the bytes fit and were written");
    claim(
        unsafe { buf.entry() }.is_none(),
        "and cannot be entered before it is armed",
    );
    claim(buf.arm(0xC0DE_1234_5678_9ABC), "arming serialises and registers");

    let Some(f) = (unsafe { buf.entry() }) else {
        claim(false, "an armed buffer has an entry point");
        return false;
    };
    // The first instruction this kernel has ever fetched from its own heap.
    let got = unsafe { f(21) };
    claim(got == 42, "it runs, and the argument arrived in rdi");

    // The registry answers for the range, which is what a fault would ask.
    let at = buf.addr();
    claim(
        lookup(at + 3) == Some((0xC0DE_1234_5678_9ABC, 3)),
        "a fault inside it would be named and offset",
    );
    claim(
        lookup(at + buf.len() as u64).is_none(),
        "and one just past the end would not",
    );
    claim(lookup(at - 1).is_none(), "nor one just before it");

    // Dropping releases the slot. Without this a freed buffer goes on
    // claiming an address range the allocator has handed to somebody else,
    // and the next fault there names a program that is not running.
    drop(buf);
    claim(lookup(at + 3).is_none(), "and dropping it releases the claim");

    ok
}
