"""Provenance for the ported wireless tree, checked rather than promised.

`src/wlan/` is not this project's work. It is transliterated from OpenBSD's
`sys/net80211`, which is 24,665 lines across 31 files under three permissive
licences and **eleven distinct copyright holders**. Carrying those notices is
the whole of what those licences ask, and the way that obligation is normally
broken is not malice: it is one file added later, in a hurry, by somebody who
knew the rule and was thinking about a bug.

So this scans and fails, the way `portcheck.py` does for the seam. Every file
under `src/wlan/` must open with a provenance block:

    //! <one line of what this file is>
    //!
    //! Ported from OpenBSD `sys/net80211/ieee80211_crypto_ccmp.c`.
    //! upstream-sha256: 0f3a...  (first 16 hex of the file as fetched)
    //! Copyright (c) 2008 Damien Bergamini <damien.bergamini@free.fr>
    //! Licence: ISC. See licenses/net80211-ISC.txt.

Four fields, and each exists because dropping it loses something specific:

  * **upstream** names the file this came from, so a later reader can diff.
  * **upstream-sha256** pins *which version* it came from. Without it,
    "ported from ieee80211_input.c" is true of every revision since 2001 and
    identifies none of them. `--fetch` records it; nothing else may.
  * **Copyright** lines are the licence obligation, verbatim and complete.
    A BSD-3 file here carries three holders and all three must appear.
  * **Licence** names the family and the file that carries its full text.

A file that is genuinely ours -- a seam shim, a test fixture, a simulated
access point -- says so instead, with `//! Written for GLaDOS.` on its own
line. That is not a loophole: it is the distinction the whole file exists to
keep legible, and it is counted and reported separately so the ratio is
visible rather than assumed.

    python tools/wlanprov.py                 # check every file
    python tools/wlanprov.py --inventory     # what came from where
    python tools/wlanprov.py --fetch DIR     # record sha256s from a checkout
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TREE = ROOT / "src" / "wlan"

# Upstream, as fetched. Regenerated by --fetch; not written by hand, because a
# hand-written digest is a digest of nothing.
UPSTREAM = "https://raw.githubusercontent.com/openbsd/src/master/sys/net80211"

OURS = re.compile(r"^//!\s*Written for GLaDOS\.\s*$", re.M)
FROM = re.compile(r"^//!\s*Ported from OpenBSD `([^`]+)`\.", re.M)
SHA = re.compile(r"^//!\s*upstream-sha256:\s*([0-9a-f]{16,64})\b", re.M)
COPY = re.compile(r"^//!\s*(Copyright \(c\).+)$", re.M)
LIC = re.compile(r"^//!\s*Licence:\s*(ISC|BSD-2|BSD-3)\b", re.M)

# The licence text files that must exist for every family actually used. Named
# here rather than discovered, so a family appearing with no text to point at
# is a failure instead of a dangling reference.
LICENCE_FILES = {
    "ISC": "licenses/net80211-ISC.txt",
    "BSD-2": "licenses/net80211-BSD-2-Clause.txt",
    "BSD-3": "licenses/net80211-BSD-3-Clause.txt",
}


def check(path: Path):
    """Every provenance fault in one file, as a list of reasons."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        return [f"unreadable: {e}"], None

    head = "\n".join(text.splitlines()[:40])

    if OURS.search(head):
        # Ours, and it must not also claim an upstream -- a file cannot be
        # both, and a block that says both is one somebody edited halfway.
        if FROM.search(head):
            return ["claims both 'Written for GLaDOS' and an upstream file"], None
        return [], None

    bad = []
    m = FROM.search(head)
    if not m:
        return [
            "no provenance block: needs 'Ported from OpenBSD `...`' "
            "or 'Written for GLaDOS.'"
        ], None

    upstream = m.group(1)
    if not SHA.search(head):
        bad.append("no upstream-sha256 -- run --fetch, do not type one")
    if not COPY.search(head):
        bad.append("no Copyright line, which is the whole licence obligation")

    lm = LIC.search(head)
    if not lm:
        bad.append("no 'Licence:' line naming ISC, BSD-2 or BSD-3")
    else:
        want = ROOT / LICENCE_FILES[lm.group(1)]
        if not want.is_file():
            bad.append(f"licence {lm.group(1)} named, but {want.name} is absent")

    return bad, (upstream, COPY.findall(head), lm.group(1) if lm else "?")


def fetch(into: Path):
    """Record the sha256 of every upstream file, from a local checkout."""
    if not into.is_dir():
        print(f"[wlanprov] {into}: not a directory")
        return 1
    rows = []
    for f in sorted(into.glob("ieee80211*.[ch]")):
        d = hashlib.sha256(f.read_bytes()).hexdigest()[:16]
        rows.append((f.name, d, len(f.read_bytes())))
    if not rows:
        print(f"[wlanprov] {into}: no ieee80211*.[ch] found")
        return 1
    print(f"# upstream: {UPSTREAM}")
    print(f"# {len(rows)} file(s)")
    for name, d, n in rows:
        print(f"{d}  {n:>7}  {name}")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", action="store_true", help="what came from where")
    ap.add_argument("--fetch", metavar="DIR", help="print sha256s from a checkout")
    args = ap.parse_args()

    if args.fetch:
        return fetch(Path(args.fetch))

    if not TREE.is_dir():
        # Same stance portcheck takes: the tree is created by the port that
        # needs it, and this script exists before it does.
        print("[wlanprov] src/wlan: not present yet")
        return 0

    files = sorted(TREE.rglob("*.rs"))
    total = 0
    ported = []
    ours = 0

    for f in files:
        bad, info = check(f)
        rel = f.relative_to(ROOT).as_posix()
        for why in bad:
            print(f"{rel}: {why}")
        total += len(bad)
        if info:
            ported.append((rel, info))
        elif not bad:
            ours += 1

    if args.inventory:
        print(f"[wlanprov] {len(ported)} ported, {ours} written here")
        for rel, (upstream, holders, lic) in ported:
            print(f"\n  {rel}")
            print(f"    from    {upstream}  ({lic})")
            for h in holders:
                print(f"    {h}")
        return 0 if total == 0 else 1

    if total:
        print()
        print(f"[wlanprov] {total} fault(s) in {len(files)} file(s).")
        print("[wlanprov] Every file under src/wlan/ says where it came from,")
        print("[wlanprov] or says 'Written for GLaDOS.' Those are the two options.")
        return 1

    print(f"[wlanprov] {len(files)} file(s) accounted for: {len(ported)} ported, {ours} ours.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
