//! Things, drawn as billboards.
//!
//! A sprite is a patch -- the same column-and-post encoding `pic.rs` already
//! decodes for wall textures -- so nothing here re-reads a picture. What is
//! here is the three things a wall never needs: finding a sprite by the
//! convention its *name* encodes, deciding which sprite a map's thing wants,
//! and clipping a billboard against geometry that was drawn before it.
//!
//! ### The name is the directory
//!
//! There is no table in a WAD saying which lumps are frames of what. A sprite
//! lump is named `NNNNFR`: four characters of sprite name, a frame letter from
//! `A`, and a rotation digit. Rotation `0` means *this picture from every
//! angle*, which is what every item and every piece of scenery uses, and 1 to
//! 8 are the eight facings a monster has. Two frames can share one lump
//! through an eight-character name -- `SARGA1D1` is frame A rotation 1 and
//! also frame D rotation 1 mirrored -- and that is not handled here.
//!
//! ### The table is generated now, and the small one was the problem
//!
//! This carried a hand-written list of 44 doomednums, on the argument that
//! copying `mobjinfo` would be copying a game's content. The argument was
//! sound and the conclusion was wrong: a doomednum means what id decided it
//! means, so a *partial* table is not a smaller version of the right answer,
//! it is a level with 49 things missing from it -- which is exactly what
//! FreeDoom E1M1 measured. `info.rs` is generated by `tools/doominfo.py` from
//! an upstream checkout, states its provenance, and carries all 118.
//!
//! ### A thing wears an animation, not a picture
//!
//! Frame `A` was hardcoded in three places here, so every torch stood still
//! and every barrel was the same barrel. What a thing actually wears is the
//! chain of states reachable from its spawn state, and **the length of that
//! chain is written down nowhere** -- DOOM stores a linked list through `next`
//! and the cycle ends by arriving somewhere it has already been. So `chain`
//! walks it, and the two ways it can stop are the two kinds of thing there
//! are: a torch closes a loop and animates forever, a medikit reaches a state
//! with negative `tics` and stands in it.
//!
//! Which frame is showing is **not** decided here. That belongs to the object
//! (`thing.rs`), because a picture chosen from the world tic is only right
//! while every barrel on the map stays in step with every other -- true today
//! and false the moment one of them can be shot. This module decodes the
//! pictures and keys them by state; the object says which state it is in.

use alloc::vec::Vec;

use super::info;
use super::level::Level;
use super::math;
use super::thing::{Obj, Objs};
use super::pic::Patch;
use super::wad::{Name, Wad};

/// The state a thing of this kind starts its life in, if it is a thing at
/// all.
///
/// A doomednum absent from the table is genuinely not an object: player and
/// deathmatch starts are map data with no `mobjinfo` row, so they answer
/// nothing here for the same reason they drew nothing before, and without a
/// second list saying which numbers to ignore.
pub fn spawn_state(kind: i16) -> Option<u16> {
    info::kind_of(kind).map(|k| k.spawn)
}

/// The states a thing cycles through, and whether the cycle closes.
///
/// Two stopping conditions, and they are the two kinds of animation DOOM has.
/// Arriving at a state already in the chain closes a **loop** -- a torch, a
/// barrel, a monster standing idle -- and the caller plays it forever.
/// Reaching negative `tics` is a state that **never advances**, which is every
/// item and every piece of scenery, and the caller stops on it.
///
/// The cap is a third condition that should never fire, and is here because
/// this walks a generated table: a chain that neither closed nor terminated
/// would hang the level load rather than draw something wrong, and a hang is
/// the one failure with no diagnostic at all.
fn chain(spawn: u16) -> (Vec<u16>, bool) {
    const CAP: usize = 32;
    let mut out: Vec<u16> = Vec::new();
    let mut st = spawn;
    let mut looped = false;
    while out.len() < CAP {
        // `S_NULL` draws nothing, and several real kinds sit in it forever.
        if st == 0 {
            break;
        }
        if out.contains(&st) {
            looped = true;
            break;
        }
        out.push(st);
        let Some(row) = info::STATES.get(st as usize) else { break };
        if row.tics < 0 {
            break;
        }
        st = row.next;
    }
    (out, looped)
}

/// Every sprite lump in the WAD, by the name it is filed under.
pub struct Sprites {
    names: Vec<Name>,
    data: Vec<&'static [u8]>,
    pub marked: bool,
}

impl Sprites {
    pub fn load(wad: &Wad) -> Sprites {
        let mut names = Vec::new();
        let mut data = Vec::new();
        let mut depth = 0usize;
        let mut marked = false;
        for i in 0..wad.len() {
            let Some(e) = wad.at(i) else { continue };
            let n = e.name.as_str();
            // The sprite namespace, `S_START`/`S_END` or a PWAD's `SS_START`.
            // Same shape as the flat rule and separate from it for the reason
            // that rule exists: the two namespaces overlap in nothing but
            // their punctuation, and a lump has to be in the right one.
            if e.is_empty() && n.starts_with('S') {
                if n.ends_with("_START") {
                    depth += 1;
                    marked = true;
                    continue;
                }
                if n.ends_with("_END") {
                    depth = depth.saturating_sub(1);
                    continue;
                }
            }
            if depth > 0 && !e.is_empty() {
                names.push(e.name);
                data.push(wad.data(e));
            }
        }
        Sprites { names, data, marked }
    }

    pub fn len(&self) -> usize {
        self.names.len()
    }

    pub fn is_empty(&self) -> bool {
        self.names.is_empty()
    }

    pub fn name_at(&self, i: usize) -> Option<&Name> {
        self.names.get(i)
    }

    pub fn index_of(&self, name: &str) -> Option<usize> {
        self.names.iter().rposition(|n| n.is(name))
    }

    pub fn bytes(&self, i: usize) -> Option<&'static [u8]> {
        self.data.get(i).copied()
    }

    /// One frame, rotation 0, of a sprite by its four-character name.
    ///
    /// Rotation 0 only, and that is the whole of what this draws. Anything
    /// with eight facings has no rotation-0 lump, so it resolves to nothing --
    /// which is a monster that does not appear rather than a monster drawn
    /// facing the wrong way, and the first is much easier to notice.
    pub fn still(&self, name: &str, frame: u8) -> Option<usize> {
        let mut buf = [0u8; 8];
        let b = name.as_bytes();
        if b.len() != 4 {
            return None;
        }
        buf[..4].copy_from_slice(b);
        buf[4] = frame;
        buf[5] = b'0';
        let full = core::str::from_utf8(&buf[..6]).ok()?;
        self.index_of(full)
    }

    /// One frame at one of the eight facings, and whether that lump is the
    /// mirror of the one wanted.
    ///
    /// A sprite lump can serve two frames at once through an eight-character
    /// name: `SARGA1D1` is frame A rotation 1, *and* frame D rotation 1 drawn
    /// mirrored. id did that because a monster is symmetric about its facing,
    /// so the picture of it turned 45 degrees left is the picture of it turned
    /// 45 degrees right flipped -- which halves the art for the four
    /// off-axis pairs. A reader that only matched the first pair would find
    /// four of the eight facings and drop the rest.
    ///
    /// A scan rather than a lookup. The list is every sprite lump in the WAD
    /// -- 853 in FreeDoom -- and this runs eight times per *sprite kind* when
    /// a level loads, not per thing and never per frame.
    pub fn facing(&self, name: &str, frame: u8, rot: u8) -> Option<(usize, bool)> {
        let want = name.as_bytes();
        if want.len() != 4 || !(1..=8).contains(&rot) {
            return None;
        }
        let digit = b'0' + rot;
        for (i, n) in self.names.iter().enumerate() {
            let s = n.as_str().as_bytes();
            if s.len() < 6 || s[..4] != want[..4] {
                continue;
            }
            if s[4] == frame && s[5] == digit {
                return Some((i, false));
            }
            if s.len() == 8 && s[6] == frame && s[7] == digit {
                return Some((i, true));
            }
        }
        None
    }
}

/// Every picture one frame of one sprite has.
///
/// A frame is either one picture seen from every angle or eight facings, and
/// which it is comes from the WAD rather than from any table: a rotation-0
/// lump means the first, its absence means the second. Decoded once per
/// *kind* and shared by every thing wearing it, because a map has hundreds of
/// things and twenty sorts of them -- decoding per thing would multiply the
/// work by fifteen and the memory with it.
pub struct Frame {
    /// One picture for every angle.
    all: Option<Patch>,
    /// The eight facings, and whether each lump is mirrored. Index 0 is the
    /// front, which is rotation *1* in a lump name.
    rot: Vec<Option<(Patch, bool)>>,
}

impl Frame {
    pub fn load(sprites: &Sprites, name: &str, frame: u8) -> Option<Frame> {
        let one = |i: usize| -> Option<Patch> {
            Patch::parse(sprites.name_at(i).copied()?, sprites.bytes(i)?)
        };
        let all = sprites.still(name, frame).and_then(one);
        let mut rot = Vec::new();
        for r in 1..=8u8 {
            rot.push(
                sprites
                    .facing(name, frame, r)
                    .and_then(|(i, flip)| Some((one(i)?, flip))),
            );
        }
        if all.is_none() && rot.iter().all(|r| r.is_none()) {
            return None;
        }
        Some(Frame { all, rot })
    }

    /// Whether this frame turns at all, for a caller that wants to say so.
    pub fn turns(&self) -> bool {
        self.all.is_none()
    }

    /// One facing by index, 0 being the front. For looking at all eight.
    pub fn at(&self, rot: usize) -> Option<(&Patch, bool)> {
        if let Some(p) = self.all.as_ref() {
            return Some((p, false));
        }
        self.rot.get(rot).and_then(|o| o.as_ref()).map(|(p, f)| (p, *f))
    }

    /// How many of the eight the WAD actually stores a lump for, and how many
    /// of those are mirrors. `SARGA2A8` is one lump serving two facings, so a
    /// monster with five lumps has eight facings and three mirrors.
    pub fn found(&self) -> (usize, usize) {
        let have = self.rot.iter().filter(|r| r.is_some()).count();
        let mirrored = self.rot.iter().filter(|r| matches!(r, Some((_, true)))).count();
        (have, mirrored)
    }

    /// Which picture the viewer sees, and whether to draw it mirrored.
    ///
    /// `to_thing` is the bearing from the eye to the thing and `facing` is the
    /// way the thing is pointing, both in radians. DOOM's own expression is
    ///
    /// ```text
    /// rot = (ang - thing->angle + (unsigned)(ANG45/2)*9) >> 29
    /// ```
    ///
    /// and the constant is what makes it work: `ANG45/2 * 9` is 202.5 degrees,
    /// which is 180 to turn "where the viewer is" into "which way the thing
    /// shows", plus 22.5 to put the *centre* of the front facing at the
    /// boundary-free middle of its bucket rather than on the edge. Without the
    /// half-bucket the sprite would flip between two facings whenever the
    /// viewer stood exactly in front of it.
    pub fn pick(&self, to_thing: f32, facing: f32) -> Option<(&Patch, bool)> {
        if let Some(p) = self.all.as_ref() {
            return Some((p, false));
        }
        let eighth = math::TAU / 8.0;
        let mut a = to_thing - facing + eighth * 4.5;
        a -= math::TAU * math::floor_i(a / math::TAU) as f32;
        let want = ((a / eighth) as usize).min(7);
        // Outward from the facing wanted, so a WAD missing one draws its
        // nearest neighbour rather than nothing. Searching one direction only
        // would bias every gap the same way round, which on a monster reads as
        // it snapping to face you.
        for k in 0..8usize {
            let step = k.div_ceil(2);
            let j = if k % 2 == 0 { want + step } else { want + 8 - step };
            if let Some((p, f)) = self.rot[j % 8].as_ref() {
                return Some((p, *f));
            }
        }
        None
    }
}

/// The things of a level: the objects, and the pictures they draw from.
///
/// The art is keyed by **state** and not by kind, which is the key that
/// survives an object leaving its spawn cycle. Decoded once and shared, which
/// is the same trade `Pics` makes and matters more here: a patch decode
/// allocates a vector per column, and a map with forty barrels on it would
/// otherwise decode forty copies of the same two pictures.
pub struct Things {
    /// The decoded pictures, one per state that had a lump.
    art: Vec<Frame>,
    /// Which picture each reachable state shows, sorted by state so a lookup
    /// is a search rather than a scan.
    ///
    /// An index and not the `Frame` itself, because **two states can share
    /// one**. A WAD is allowed to be incomplete, and a state whose lump is
    /// missing falls back to the last one that had a picture rather than
    /// drawing nothing -- the same judgement `Frame::pick` makes about a
    /// missing facing, and for a better reason than tidiness: drawing nothing
    /// on alternate frames makes a thing *flicker*, which reads as a renderer
    /// fault and not as a WAD that is short of a lump.
    ///
    /// This was found by the test fixture, which ships `BAR1A0` and no
    /// `BAR1B0` while a barrel's cycle is A then B. Every barrel in it was
    /// vanishing for six tics in twelve, and FreeDoom hid the fault completely
    /// by having every frame a thing could ask for.
    by_state: Vec<(u16, usize)>,
    /// Every object on the level.
    pub objs: Objs,
    /// How many distinct kinds turn to face the viewer, and how many have more
    /// than one frame. Counted at load, because afterwards the objects are
    /// what exist and the kinds are not enumerated anywhere.
    turning: usize,
    animated: usize,
    /// How many distinct kinds stand on the level.
    ///
    /// Not `art.len()`, which is a count of *states*: one kind contributes as
    /// many pictures as its cycle is long, so 44 kinds on FreeDoom E1M1 decode
    /// 66 of them. Reporting the second under the first's name reads as a
    /// level with half again as many sorts of thing on it as it has.
    kinds: usize,
}

impl Things {
    /// Nothing to draw, for a WAD with no sprite namespace at all.
    pub fn none() -> Things {
        Things {
            art: Vec::new(),
            by_state: Vec::new(),
            objs: Objs::new(),
            turning: 0,
            animated: 0,
            kinds: 0,
        }
    }

    pub fn len(&self) -> usize {
        self.objs.len()
    }

    pub fn is_empty(&self) -> bool {
        self.objs.is_empty()
    }

    /// The pictures for one state, if this level decoded any.
    pub fn frame(&self, state: u16) -> Option<&Frame> {
        let i = self.by_state.binary_search_by_key(&state, |(s, _)| *s).ok()?;
        self.art.get(self.by_state[i].1)
    }

    /// How many of the kinds on this level turn to face the viewer.
    pub fn turning(&self) -> usize {
        self.turning
    }

    /// How many of them have more than one picture, for a caller that wants to
    /// report that anything moves at all.
    pub fn animated(&self) -> usize {
        self.animated
    }

    /// How many distinct sprite kinds the level draws from.
    pub fn kinds(&self) -> usize {
        self.kinds
    }

    /// How many distinct states can be drawn.
    pub fn states(&self) -> usize {
        self.by_state.len()
    }

    /// How many pictures were actually decoded, which is fewer whenever a WAD
    /// is short of a frame and a state had to borrow one.
    pub fn pictures(&self) -> usize {
        self.art.len()
    }

    /// One tic of every object's own clock, reporting what fired.
    pub fn tick(&mut self, out: &mut Vec<super::thing::Fired>) {
        self.objs.tick(out);
    }

    /// The states every object is in, added up. See `Objs::phase`.
    pub fn phase(&self) -> usize {
        self.objs.phase()
    }
}

/// Decode every drawable thing on the level, once.
pub fn collect(lv: &Level, sprites: &Sprites) -> Things {
    let mut art: Vec<Frame> = Vec::new();
    let mut by_state: Vec<(u16, usize)> = Vec::new();
    let mut objs = Objs::new();
    // Which kinds have been met, so the art for a second imp is not decoded
    // again and the two counters below are per kind rather than per thing.
    let mut seen: Vec<u16> = Vec::new();
    let (mut turning, mut animated) = (0usize, 0usize);

    for t in lv.things.iter() {
        let Some(row) = info::row_of(t.kind) else { continue };
        // The sector it is standing in. A thing whose sector cannot be found
        // is dropped rather than placed at zero, which in a map with a raised
        // floor would bury it.
        let Some(sector) = lv.sector_index_at(t.x as i32, t.y as i32) else { continue };
        let Some(o) = Obj::spawn(
            row,
            t.x as f32,
            t.y as f32,
            math::deg_to_rad(t.angle),
            sector,
        ) else {
            continue;
        };

        if !seen.contains(&row) {
            seen.push(row);
            // Every state this kind can reach today, which is its spawn cycle
            // and nothing else. The kinds that can reach further -- a monster
            // walking, hurting, dying -- get their chains decoded by the phase
            // that gives them somewhere to walk to; decoding all eight chains
            // of every kind now would be several thousand patch decodes at
            // level load for pictures nothing can ask for.
            let (states, _) = chain(info::KINDS[row as usize].spawn);
            let mut have = 0usize;
            let mut turns = false;
            // The picture this kind falls back to when a state has no lump.
            // The *previous* one in the chain, so a gap borrows the frame
            // before it rather than the kind's first frame -- which for a long
            // animation with one lump missing is much less visible.
            let mut last: Option<usize> = None;
            for st in states.iter() {
                if let Some(k) = by_state.iter().find(|(s, _)| s == st).map(|(_, i)| *i) {
                    last = Some(k);
                    have += 1;
                    continue;
                }
                let picture = match info::frame_of(*st)
                    .and_then(|(name, letter)| Frame::load(sprites, name, letter))
                {
                    Some(f) => {
                        turns |= f.turns();
                        art.push(f);
                        have += 1;
                        art.len() - 1
                    }
                    // No lump. Borrow, and do not count it as a picture this
                    // kind has -- a kind whose second frame is missing does
                    // not animate, whatever the table says.
                    None => match last {
                        Some(k) => k,
                        None => continue,
                    },
                };
                by_state.push((*st, picture));
                last = Some(picture);
            }
            if turns {
                turning += 1;
            }
            if have > 1 {
                animated += 1;
            }
        }

        // A kind whose pictures are all missing draws nothing, so the object
        // is not kept: an invisible thing that still occupies the sort and the
        // clock is a cost with no picture at the end of it.
        if by_state.iter().any(|(s, _)| *s == o.state) {
            objs.list.push(o);
        }
    }

    by_state.sort_unstable_by_key(|(s, _)| *s);
    let kinds = seen.len();
    Things { art, by_state, objs, turning, animated, kinds }
}

/// Numbers a map places that are not objects.
///
/// Where a player enters and where deathmatch players enter. These are the
/// only ones: they are positions the map format defines, they have no
/// `mobjinfo` row, and nothing ever spawns from them. A teleport destination
/// looks like it belongs here and does not -- it is a real object with a real
/// row, and what makes it invisible is that its row spawns into `S_NULL`.
///
/// The list exists so a census can tell "a placeholder" from "a doomednum
/// nothing has a row for", which are the same answer from `info::row_of` and
/// very different news. The first is every map ever made; the second is a
/// thing that will not appear.
fn map_data(kind: i16) -> bool {
    matches!(kind, 1..=4 | 11)
}

/// What a level's things decompose to: drawn, placeholders, doomednums with
/// no row, and rows whose art this WAD does not have.
///
/// The third figure is the one worth printing. It was 49 on FreeDoom E1M1
/// against the hand-written table and is 0 against the generated one, so it is
/// what says whether the table is actually being consulted -- and it would go
/// back up the moment somebody loaded a PWAD with custom things in it, which
/// is the honest answer rather than a bug.
pub fn census(lv: &Level, sprites: &Sprites) -> (usize, usize, usize, usize) {
    let (mut drawn, mut placed, mut no_kind, mut no_lump) = (0, 0, 0, 0);
    for t in lv.things.iter() {
        let Some(row) = info::row_of(t.kind) else {
            if map_data(t.kind) {
                placed += 1;
            } else {
                no_kind += 1;
            }
            continue;
        };
        // A kind draws if any state of its cycle has any picture: a rotation-0
        // lump, or at least one of the eight facings.
        let (states, _) = chain(info::KINDS[row as usize].spawn);
        let any = states.iter().any(|st| {
            info::frame_of(*st).is_some_and(|(n, l)| Frame::load(sprites, n, l).is_some())
        });
        if any {
            drawn += 1;
        } else {
            no_lump += 1;
        }
    }
    (drawn, placed, no_kind, no_lump)
}

/// What `diag doom` asks of the state table and the chain walk.
///
/// Every one of these is arithmetic over a generated table, so none needs a
/// WAD and all of them run at boot. That is the whole reason to check here
/// rather than by looking at a torch: a flicker is visible only to somebody
/// watching, and a chain that failed to terminate would not flicker, it would
/// hang the level load.
pub fn checks() -> Vec<(&'static str, bool)> {
    let mut out: Vec<(&'static str, bool)> = Vec::new();

    // Every kind's cycle terminates. The cap in `chain` is a backstop against
    // a table this walk cannot make sense of, and reaching it on stock content
    // would mean the generator emitted something wrong -- so the claim is that
    // it is never reached, not that it exists.
    let mut longest = 0usize;
    let mut capped = 0usize;
    for k in info::KINDS.iter() {
        let (c, _) = chain(k.spawn);
        longest = longest.max(c.len());
        if c.len() >= 32 {
            capped += 1;
        }
    }
    out.push(("every spawn cycle terminates", capped == 0 && longest > 0));

    // A zombieman stands in a two-frame loop. The pair is `S_POSS_STND` and
    // `S_POSS_STND2` pointing at each other, which is the shape every idle
    // monster in the game has and the one a walk could most easily run past.
    let (poss, looped) = spawn_state(3004).map(chain).unwrap_or((Vec::new(), false));
    out.push(("a zombieman idles in a loop of two", poss.len() == 2 && looped));

    // A barrel animates and a medikit does not, which is the distinction the
    // whole of `Anim` rests on: one closes a loop, the other reaches a state
    // with negative `tics` and stops.
    let (barrel, barrel_loops) = spawn_state(2035).map(chain).unwrap_or((Vec::new(), false));
    let (medi, medi_loops) = spawn_state(2012).map(chain).unwrap_or((Vec::new(), true));
    out.push(("a barrel loops, a medikit stands still",
              barrel.len() > 1 && barrel_loops && medi.len() == 1 && !medi_loops));

    // The frame field is a number and the lump is named by a letter. Getting
    // this wrong reads as a thing with no picture rather than as an error,
    // because the WAD simply has no lump by the name asked for.
    let poss_a = poss.first().and_then(|s| info::frame_of(*s));
    out.push(("a state names its sprite and frame letter",
              poss_a == Some(("POSS", b'A'))));

    // `S_NULL` carries a sprite and a frame like any other row, and several
    // real kinds sit in it. Drawing what the fields say would put an imp on
    // every teleport pad on the map.
    out.push(("state zero draws nothing", info::frame_of(0).is_none()));

    // Map data is not a thing, and the two halves of that come apart here.
    // Player and deathmatch starts have no `mobjinfo` row at all, so they are
    // absent by construction rather than by a second list of exceptions. A
    // teleport destination *does* have a row -- it is a real object with a
    // real doomednum whose whole job is to be a marker -- and what makes it
    // invisible is that its row spawns into `S_NULL`.
    out.push((
        "a player start is not a kind",
        spawn_state(1).is_none() && spawn_state(2).is_none() && spawn_state(11).is_none(),
    ));
    out.push((
        "a teleport destination is a kind that draws nothing",
        spawn_state(14).is_some_and(|s| info::frame_of(s).is_none()),
    ));

    // A number no table has a row for. The generated table carries 118 of
    // them, so this is no longer the common case it was, but a PWAD is free
    // to place anything.
    out.push(("an unknown doomednum draws nothing", spawn_state(31337).is_none()));

    // The scenery claim that used to live in `pic::checks`, which is where
    // the sprite checks were kept before this module had any of its own.
    out.push((
        "a scenery thing resolves to its sprite",
        spawn_state(2035).and_then(info::frame_of).map(|(n, _)| n) == Some("BAR1")
            && spawn_state(2028).and_then(info::frame_of).map(|(n, _)| n) == Some("COLU"),
    ));

    out
}
