//! Whether a staged image is one this machine will run.
//!
//! The update itself is applied before `ExitBootServices`, by the firmware's
//! own FAT driver, because that is the only writer of the ESP that exists
//! while a boot image can still be replaced. This module answers the question
//! that has to be settled *first*: is the thing on disk signed by the key this
//! kernel trusts.
//!
//! ### Where the trust anchor lives, and why
//!
//! `UPDATE_KEY` is compiled into the running kernel. It is deliberately not a
//! file on the ESP beside the image, because anyone able to replace the image
//! could replace a key file just as easily, and a signature checked against a
//! key the attacker supplied is a signature checked against nothing. Pinning
//! it means forging an update requires already being able to rewrite the
//! running kernel -- at which point the signature was never the weak part.
//!
//! The cost is that rotating the key needs a kernel update, signed by the old
//! key. That is the right way round.
//!
//! ### Failing closed
//!
//! An all-zero key means no key has been provisioned, and every verification
//! then **refuses**. A mechanism that accepts everything until configured is a
//! mechanism that ships disabled and looks enabled.

use crate::crypto::p256;
use crate::store::sha256;

/// `"GLADOSIG"`, a version, a curve, then r and s.
const MAGIC: &[u8; 8] = b"GLADOSIG";
pub const SIG_LEN: usize = 8 + 4 + 4 + 32 + 32;

/// The public key this kernel will accept updates from, uncompressed
/// (`0x04 || X || Y`).
///
/// Generated by `tools/sign.py --keygen`; the private half never touches the
/// machine being updated. Replace this to adopt a different signer -- and note
/// that doing so is itself a kernel change, which is the point.
/// **Unprovisioned on purpose, and this is the safe state.**
///
/// A key was pinned here during development and its private half was printed
/// to a terminal while the signer was being written. A trust anchor whose
/// private half has been seen is not a trust anchor -- it is an invitation
/// that looks like a lock, and the failure mode is the worst one available: a
/// machine that reports a forged update as correctly signed. Zeroed is
/// strictly better, because `have_key` then refuses *everything* and says so.
///
/// To provision one:
///
/// ```text
///     python tools/sign.py --keygen
/// ```
///
/// Paste the public rows here, keep the private half off every machine that
/// will ever apply an update, and rebuild. The rebuild is the point: adopting
/// a signer is itself a kernel change, so it arrives the same way every other
/// kernel change does.
pub const UPDATE_KEY: [u8; 65] = [0u8; 65];

/// Every way this can end, so a caller cannot collapse them into a bool and
/// lose the difference between "not signed" and "signed by somebody else".
#[derive(Clone, Copy, PartialEq)]
pub enum Verdict {
    /// Signed by the pinned key, over exactly these bytes.
    Good,
    /// No key is compiled in, so nothing can be trusted.
    NoKey,
    /// The signature file is not one of ours, or is the wrong length.
    Malformed,
    /// A format or curve this kernel does not implement. Refused rather than
    /// guessed at, so a future format cannot be silently misread as this one.
    Unsupported,
    /// Well formed, and not a signature over this image by this key.
    Bad,
}

impl Verdict {
    pub fn ok(self) -> bool {
        self == Verdict::Good
    }

    pub fn why(self) -> &'static str {
        match self {
            Verdict::Good => "signed by the update key",
            Verdict::NoKey => "no update key is compiled in -- refusing everything",
            Verdict::Malformed => "not a GLADOSIG signature",
            Verdict::Unsupported => "a signature format this kernel does not implement",
            Verdict::Bad => "not a signature over this image by this key",
        }
    }
}

fn have_key() -> bool {
    UPDATE_KEY[0] == 0x04 && UPDATE_KEY[1..].iter().any(|b| *b != 0)
}

/// Check a detached signature over an image.
///
/// The digest is SHA-256 over *all* of `image`, so the signature commits to
/// every byte: a truncated image fails rather than verifying as a shorter
/// valid one.
pub fn verify(image: &[u8], sig: &[u8]) -> Verdict {
    if !have_key() {
        return Verdict::NoKey;
    }
    if sig.len() != SIG_LEN || &sig[..8] != MAGIC {
        return Verdict::Malformed;
    }
    let version = u32::from_le_bytes([sig[8], sig[9], sig[10], sig[11]]);
    let curve = u32::from_le_bytes([sig[12], sig[13], sig[14], sig[15]]);
    if version != 1 || curve != 0 {
        return Verdict::Unsupported;
    }
    let digest = sha256::hash(image);
    if p256::verify(p256::Nist::P256, &UPDATE_KEY, &digest, &sig[16..48], &sig[48..80]) {
        Verdict::Good
    } else {
        Verdict::Bad
    }
}

/// The refusals, checked without needing a signer.
///
/// Only the negative half is provable here: producing a good signature needs
/// the private key, which by design is not on this machine. The positive case
/// is proved by `tools/sign.py` against a real image, and is the one thing
/// about this module that cannot be checked at boot -- said plainly rather
/// than left as a gap somebody has to notice.
///
/// A verifier that refuses everything passes every test below, so these claims
/// are necessary and are nowhere near sufficient. That is why the flipped-bit
/// case exists: it is the one that distinguishes "checks the signature" from
/// "checks the magic".
pub fn selftest() -> bool {
    use crate::kprintln;
    let image = b"a staged image, or something pretending to be one";

    let mut ok = true;
    let mut claim = |what: &str, good: bool| {
        if !good {
            ok = false;
        }
        kprintln!("  {}  {}", if good { "ok " } else { "FAIL" }, what);
    };

    // With no key provisioned, *every* verdict is NoKey and the claims below
    // about format handling cannot be reached -- so the claim is that nothing
    // gets through, which is the whole of what this module promises until
    // somebody pins a signer.
    if !have_key() {
        claim(
            "no update key is provisioned, so every image is refused",
            verify(image, &[]) == Verdict::NoKey
                && verify(image, &[0u8; SIG_LEN]) == Verdict::NoKey,
        );
        kprintln!("       'python tools/sign.py --keygen' and paste into UPDATE_KEY to enable");
        return ok;
    }

    claim("an empty signature is refused", verify(image, &[]) == Verdict::Malformed);
    claim(
        "a signature of the right length but wrong magic is refused",
        verify(image, &[0u8; SIG_LEN]) == Verdict::Malformed,
    );

    let mut wrong_version = [0u8; SIG_LEN];
    wrong_version[..8].copy_from_slice(MAGIC);
    wrong_version[8] = 2;
    claim(
        "a future format is refused rather than guessed at",
        verify(image, &wrong_version) == Verdict::Unsupported,
    );

    let mut zeros = [0u8; SIG_LEN];
    zeros[..8].copy_from_slice(MAGIC);
    zeros[8] = 1;
    claim(
        "a well-formed signature of zeroes is not a signature",
        verify(image, &zeros) == Verdict::Bad,
    );

    ok
}
