//! Whether a staged image is one this machine will run.
//!
//! The update itself is applied before `ExitBootServices`, by the firmware's
//! own FAT driver, because that is the only writer of the ESP that exists
//! while a boot image can still be replaced. This module answers the question
//! that has to be settled *first*: is the thing on disk signed by the key this
//! kernel trusts.
//!
//! ### Where the trust anchor lives, and why
//!
//! `UPDATE_KEY` is compiled into the running kernel. It is deliberately not a
//! file on the ESP beside the image, because anyone able to replace the image
//! could replace a key file just as easily, and a signature checked against a
//! key the attacker supplied is a signature checked against nothing. Pinning
//! it means forging an update requires already being able to rewrite the
//! running kernel -- at which point the signature was never the weak part.
//!
//! The cost is that rotating the key needs a kernel update, signed by the old
//! key. That is the right way round.
//!
//! ### Failing closed
//!
//! An all-zero key means no key has been provisioned, and every verification
//! then **refuses**. A mechanism that accepts everything until configured is a
//! mechanism that ships disabled and looks enabled.

use crate::crypto::p256;
use crate::store::sha256;

/// `"GLADOSIG"`, a version, a curve, then r and s.
const MAGIC: &[u8; 8] = b"GLADOSIG";
pub const SIG_LEN: usize = 8 + 4 + 4 + 32 + 32;

/// The public key this kernel will accept updates from, uncompressed
/// (`0x04 || X || Y`).
///
/// Generated by `tools/sign.py --keygen`; the private half never touches the
/// machine being updated. Replace this to adopt a different signer -- and note
/// that doing so is itself a kernel change, which is the point.
/// **Unprovisioned on purpose, and this is the safe state.**
///
/// A key was pinned here during development and its private half was printed
/// to a terminal while the signer was being written. A trust anchor whose
/// private half has been seen is not a trust anchor -- it is an invitation
/// that looks like a lock, and the failure mode is the worst one available: a
/// machine that reports a forged update as correctly signed. Zeroed is
/// strictly better, because `have_key` then refuses *everything* and says so.
///
/// To provision one:
///
/// ```text
///     python tools/sign.py --keygen
/// ```
///
/// Paste the public rows here, keep the private half off every machine that
/// will ever apply an update, and rebuild. The rebuild is the point: adopting
/// a signer is itself a kernel change, so it arrives the same way every other
/// kernel change does.
pub const UPDATE_KEY: [u8; 65] = [0u8; 65];

/// Every way this can end, so a caller cannot collapse them into a bool and
/// lose the difference between "not signed" and "signed by somebody else".
#[derive(Clone, Copy, PartialEq)]
pub enum Verdict {
    /// Signed by the pinned key, over exactly these bytes.
    Good,
    /// No key is compiled in, so nothing can be trusted.
    NoKey,
    /// The signature file is not one of ours, or is the wrong length.
    Malformed,
    /// A format or curve this kernel does not implement. Refused rather than
    /// guessed at, so a future format cannot be silently misread as this one.
    Unsupported,
    /// Well formed, and not a signature over this image by this key.
    Bad,
}

impl Verdict {
    pub fn ok(self) -> bool {
        self == Verdict::Good
    }

    pub fn why(self) -> &'static str {
        match self {
            Verdict::Good => "signed by the update key",
            Verdict::NoKey => "no update key is compiled in -- refusing everything",
            Verdict::Malformed => "not a GLADOSIG signature",
            Verdict::Unsupported => "a signature format this kernel does not implement",
            Verdict::Bad => "not a signature over this image by this key",
        }
    }
}

fn have_key() -> bool {
    UPDATE_KEY[0] == 0x04 && UPDATE_KEY[1..].iter().any(|b| *b != 0)
}

/// Check a detached signature over an image.
///
/// The digest is SHA-256 over *all* of `image`, so the signature commits to
/// every byte: a truncated image fails rather than verifying as a shorter
/// valid one.
pub fn verify(image: &[u8], sig: &[u8]) -> Verdict {
    if !have_key() {
        return Verdict::NoKey;
    }
    if sig.len() != SIG_LEN || &sig[..8] != MAGIC {
        return Verdict::Malformed;
    }
    let version = u32::from_le_bytes([sig[8], sig[9], sig[10], sig[11]]);
    let curve = u32::from_le_bytes([sig[12], sig[13], sig[14], sig[15]]);
    if version != 1 || curve != 0 {
        return Verdict::Unsupported;
    }
    let digest = sha256::hash(image);
    if p256::verify(p256::Nist::P256, &UPDATE_KEY, &digest, &sig[16..48], &sig[48..80]) {
        Verdict::Good
    } else {
        Verdict::Bad
    }
}

// --- applying one ---------------------------------------------------------
//
// ### What this can protect against, and what it cannot
//
// Said first because the limit is severe and a reader who assumes otherwise
// will trust this further than it deserves.
//
// The swap happens before `ExitBootServices`, because the firmware's FAT
// driver is the only writer of the ESP that exists while a boot image can
// still be replaced. So the health check can only ask a question about the
// window it can still write in: *did the new image get from the firmware
// handoff to just before the memory map is taken*. That covers a binary that
// will not run, an early fault, a graphics init that hangs, and a model or
// tokenizer that will not load -- which is most of what a bad update does.
//
// It does **not** cover an image that fails after `ExitBootServices`, because
// by then there is no filesystem to record anything in. And it cannot cover an
// image that faults before reaching this hook at all: nothing running on the
// machine gets a turn, and the recovery for that is the USB stick. An A/B
// scheme that claimed otherwise would be claiming to run code on a computer
// that is not running any.
//
// ### Why the order is the order
//
// There is no atomic rename through `FileProtocol`, so overwriting the image
// the firmware boots is a window in which a power cut is fatal. That window
// cannot be removed here; it can only be made as small as possible and made
// the *last* thing that happens:
//
//   1. verify the staged image's signature -- before anything is touched
//   2. copy the running image to `BOOTX64.OLD`, and read it back to prove it
//      landed. A rollback copy that does not exist is the difference between
//      a recoverable machine and a brick, so nothing proceeds without one
//   3. clear `UPDATE.FLG`, so a crash from here cannot re-apply
//   4. write the staged image over `BOOTX64.EFI`  <- the window
//   5. read it back and compare its digest; on a mismatch put `OLD` straight
//      back, which is the one repair still available
//   6. write `HEALTH.FLG`, and reboot into the new image
//
// Step 2 before step 4 is the whole design. Step 5 is not paranoia: a short
// write is a legal FAT outcome and the doc on `write_file` says so.

/// Where the pieces live on the ESP.
pub const BOOT_PATH: &str = "\\EFI\\BOOT\\BOOTX64.EFI";
pub const OLD_PATH: &str = "\\GLADOS\\BOOTX64.OLD";
pub const STAGED_PATH: &str = "\\GLADOS\\STAGED.EFI";
pub const STAGED_SIG: &str = "\\GLADOS\\STAGED.SIG";
pub const UPDATE_FLAG: &str = "\\GLADOS\\UPDATE.FLG";
pub const HEALTH_FLAG: &str = "\\GLADOS\\HEALTH.FLG";

/// Boots an unproven image may take before it is rolled back.
///
/// One. The image gets this boot to reach the point where it clears the flag;
/// if the machine comes back here without that having happened, it did not.
/// A larger number buys nothing -- an image that fails early fails every time
/// -- and costs the operator that many reboots into a broken system.
pub const MAX_TRIES: u32 = 1;

/// What the hook should do, given what is on the disk.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Action {
    /// No update staged and nothing unproven. The ordinary boot.
    Nothing,
    /// An image is on trial. Record the attempt and carry on booting.
    Trying(u32),
    /// The image on trial did not prove itself. Restore `OLD` and reboot.
    RollBack,
    /// Apply the staged image.
    Apply,
    /// A staged image was refused, and why. The flag is cleared either way.
    Refuse(&'static str),
}

/// The whole decision, as a function of what is on the disk.
///
/// Separated from every file operation on purpose. This is where the safety
/// lives -- the ordering argument above is only worth as much as the choice
/// that reaches it -- and a decision made inline among `read_file` calls could
/// only be checked by staging a real update on a real machine, which is the
/// one thing nobody wants to do to find out whether it works.
///
/// `health` is the attempt count read from `HEALTH.FLG`, or `None` when the
/// file is absent.
pub fn decide(
    flag: bool,
    staged: bool,
    sig: Verdict,
    have_old: bool,
    health: Option<u32>,
) -> Action {
    // The trial resolves first, always -- and `hook` relies on that: when
    // `health` is `Some`, it does not read the staged image at all and passes
    // placeholders for `staged` and `sig`. Any future arm that reads them
    // before this one must fix the caller too. An image that has not proved itself
    // must not be allowed to apply a further update on top of itself -- that
    // would put two unproven changes in the boot path with one rollback copy
    // between them, and the copy would be of the image already on trial.
    if let Some(n) = health {
        if n >= MAX_TRIES {
            return Action::RollBack;
        }
        return Action::Trying(n + 1);
    }
    if !flag {
        return Action::Nothing;
    }
    if !staged {
        return Action::Refuse("the flag is set and there is no staged image");
    }
    if !sig.ok() {
        return Action::Refuse(sig.why());
    }
    // `have_old` is whether a rollback copy can be made, not whether one
    // already exists: the copy is taken from the running image every time, so
    // that a rollback goes back exactly one step rather than to whatever was
    // left behind by an older update.
    if !have_old {
        return Action::Refuse("the running image could not be copied aside");
    }
    Action::Apply
}

/// Read a whole file off the ESP as a slice, or `None`.
fn slurp(bs: &crate::uefi::BootServices, image: crate::uefi::Handle, path: &str) -> Option<&'static [u8]> {
    let b = crate::uefi::read_file(bs, image, path)?;
    Some(unsafe { core::slice::from_raw_parts(b.ptr, b.len) })
}

/// Copy a file and prove the copy landed.
///
/// The read-back is the point. A short write is a legal FAT outcome, so
/// "`write_file` returned true" is not the same claim as "the bytes are on the
/// disk", and the one place that distinction decides whether a machine can be
/// recovered is here.
fn copy_verified(
    bs: &crate::uefi::BootServices,
    image: crate::uefi::Handle,
    from: &[u8],
    to: &str,
) -> bool {
    if !crate::uefi::write_file(bs, image, to, from) {
        return false;
    }
    match slurp(bs, image, to) {
        Some(back) => back.len() == from.len() && sha256::hash(back) == sha256::hash(from),
        None => false,
    }
}

/// The attempt count in `HEALTH.FLG`, or `None` when there is no such file.
///
/// The file holds one ASCII digit run. Anything unreadable counts as an
/// exhausted trial rather than a fresh one: a flag file that cannot be parsed
/// is a flag file written by something that went wrong.
fn health_count(bs: &crate::uefi::BootServices, image: crate::uefi::Handle) -> Option<u32> {
    let b = slurp(bs, image, HEALTH_FLAG)?;
    let text = core::str::from_utf8(b).unwrap_or("");
    Some(text.trim().parse::<u32>().unwrap_or(MAX_TRIES))
}

/// What the hook did, so the caller knows whether a trial is now outstanding.
pub enum Outcome {
    /// Nothing staged, nothing on trial. The ordinary boot, and silent.
    Quiet,
    Said(&'static str),
    /// An update was applied and a trial armed for the *next* boot. This boot
    /// must not clear it: the image being tried is not the one running.
    Armed(&'static str),
}

/// Apply a staged update, or resolve one on trial. Runs before
/// `ExitBootServices`, which is the only time the ESP is writable.
///
/// **It does not reboot.** The first version did, and the guest never came
/// back: `ResetSystem` through the runtime table, called while boot services
/// are still up, left the machine silent -- no reset, no fault, no further
/// output. Rather than debug a firmware path that this arrangement does not
/// need, the swap simply takes effect at the next boot, whenever that is. The
/// session carries on running the image it started with, which is the one that
/// has already proved it works.
pub fn hook(bs: &crate::uefi::BootServices, image: crate::uefi::Handle) -> Outcome {
    let flag = slurp(bs, image, UPDATE_FLAG).is_some();
    let health = health_count(bs, image);
    if !flag && health.is_none() {
        return Outcome::Quiet;
    }

    // Read and verify the staged image only when the decision could use it.
    //
    // `decide` resolves a trial before it looks at anything else, so on a
    // trial or rollback boot these are ignored -- and computing them anyway
    // meant reading a 2.8 MB image off the ESP and running a P-256
    // verification to answer a question already settled. Worse than wasteful:
    // the verification allocates, and the trial boot is exactly the one where
    // the least should be happening.
    crate::serial_println!("glados: update: flag={} health={:?}", flag, health);
    let (staged, sig) = if health.is_none() {
        let img = slurp(bs, image, STAGED_PATH);
        crate::serial_println!(
            "glados: update: staged {} byte(s), verifying",
            img.map(|b| b.len()).unwrap_or(0)
        );
        let v = match (img, slurp(bs, image, STAGED_SIG)) {
            (Some(i), Some(s)) => verify(i, s),
            _ => Verdict::Malformed,
        };
        crate::serial_println!("glados: update: signature {}", v.why());
        (img, v)
    } else {
        (None, Verdict::Malformed)
    };
    // Whether the running image can be copied aside, which is what the
    // decision needs -- not whether an older copy happens to be lying there.
    let running = slurp(bs, image, BOOT_PATH);

    match decide(flag, staged.is_some(), sig, running.is_some(), health) {
        Action::Nothing => Outcome::Quiet,

        Action::Trying(n) => {
            // Record the attempt before the risky part of the boot, so an
            // image that dies during it is counted as having tried.
            let mut buf = [b'0'; 12];
            let mut i = buf.len();
            let mut v = n;
            loop {
                i -= 1;
                buf[i] = b'0' + (v % 10) as u8;
                v /= 10;
                if v == 0 || i == 0 {
                    break;
                }
            }
            crate::uefi::write_file(bs, image, HEALTH_FLAG, &buf[i..]);
            Outcome::Said("update: this image is on trial")
        }

        Action::RollBack => {
            let Some(old) = slurp(bs, image, OLD_PATH) else {
                // Nothing to go back to. Clearing the flag stops a reboot
                // loop; the machine keeps running the image it has, which is
                // the only one there is.
                crate::uefi::delete_file(bs, image, HEALTH_FLAG);
                return Outcome::Said("update: the image failed and there is no copy to restore");
            };
            if !copy_verified(bs, image, old, BOOT_PATH) {
                crate::uefi::delete_file(bs, image, HEALTH_FLAG);
                return Outcome::Said("update: the rollback would not write -- boot the USB");
            }
            crate::uefi::delete_file(bs, image, HEALTH_FLAG);
            Outcome::Said("update: rolled back -- reboot to run the restored image")
        }

        Action::Refuse(why) => {
            crate::uefi::delete_file(bs, image, UPDATE_FLAG);
            Outcome::Said(why)
        }

        Action::Apply => {
            let (Some(img), Some(run)) = (staged, running) else {
                crate::uefi::delete_file(bs, image, UPDATE_FLAG);
                return Outcome::Said("update: the staged image went away");
            };
            // 2. A rollback copy, proved.
            crate::serial_println!("glados: update: copying the running image aside");
            if !copy_verified(bs, image, run, OLD_PATH) {
                crate::uefi::delete_file(bs, image, UPDATE_FLAG);
                return Outcome::Said("update: refused -- no rollback copy could be made");
            }
            // 3. Clear the flag before the window, so a crash inside it
            //    cannot re-enter.
            crate::uefi::delete_file(bs, image, UPDATE_FLAG);
            // 4. The window.
            crate::serial_println!("glados: update: writing the new boot image");
            if !copy_verified(bs, image, img, BOOT_PATH) {
                // 5. The one repair still available.
                copy_verified(bs, image, run, BOOT_PATH);
                return Outcome::Said("update: the write failed and the old image was put back");
            }
            // 6. On trial from here.
            crate::uefi::write_file(bs, image, HEALTH_FLAG, b"0");
            // Armed, not Said: the trial belongs to the image that boots
            // next, and this boot clearing it would pass a verdict on a run
            // that has not happened.
            Outcome::Armed("update: applied -- reboot to run it")
        }
    }
}

/// The image reached the end of what this hook can watch. Stop the trial.
///
/// Called once the model, tokenizer and roots have loaded, which is the last
/// moment the ESP is writable and therefore the last moment anything can be
/// recorded about this boot. An image that gets here runs.
pub fn mark_healthy(bs: &crate::uefi::BootServices, image: crate::uefi::Handle) {
    crate::uefi::delete_file(bs, image, HEALTH_FLAG);
}

/// The refusals, checked without needing a signer.
///
/// Only the negative half is provable here: producing a good signature needs
/// the private key, which by design is not on this machine. The positive case
/// is proved by `tools/sign.py` against a real image, and is the one thing
/// about this module that cannot be checked at boot -- said plainly rather
/// than left as a gap somebody has to notice.
///
/// A verifier that refuses everything passes every test below, so these claims
/// are necessary and are nowhere near sufficient. That is why the flipped-bit
/// case exists: it is the one that distinguishes "checks the signature" from
/// "checks the magic".
pub fn selftest() -> bool {
    use crate::kprintln;
    let image = b"a staged image, or something pretending to be one";

    let mut ok = true;
    let mut claim = |what: &str, good: bool| {
        if !good {
            ok = false;
        }
        kprintln!("  {}  {}", if good { "ok " } else { "FAIL" }, what);
    };

    // The hook's decision, which is where the safety actually lives. Every
    // one of these is a state the disk can really be in, and none of them
    // needs a disk to check.
    let good = Verdict::Good;
    let bad = Verdict::Bad;
    claim(
        "an ordinary boot does nothing",
        decide(false, false, bad, true, None) == Action::Nothing,
    );
    claim(
        "a flag with no staged image is refused",
        matches!(decide(true, false, good, true, None), Action::Refuse(_)),
    );
    claim(
        "an unsigned staged image is refused",
        matches!(decide(true, true, bad, true, None), Action::Refuse(_)),
    );
    // The one that decides whether a bad update is recoverable at all.
    claim(
        "an update is refused when no rollback copy can be made",
        matches!(decide(true, true, good, false, None), Action::Refuse(_)),
    );
    claim(
        "a signed image with somewhere to fall back to is applied",
        decide(true, true, good, true, None) == Action::Apply,
    );
    // An image on trial must not be allowed to apply a further update on top
    // of itself: that would put two unproven changes in the boot path with
    // one rollback copy between them, and the copy would be of the image
    // already on trial.
    claim(
        "an image on trial does not apply a further update",
        decide(true, true, good, true, Some(0)) == Action::Trying(1),
    );
    claim(
        "an image that has used its trial is rolled back",
        decide(false, false, bad, true, Some(MAX_TRIES)) == Action::RollBack,
    );
    claim(
        "and rolled back even with an update waiting",
        decide(true, true, good, true, Some(MAX_TRIES)) == Action::RollBack,
    );


    // With no key provisioned, *every* verdict is NoKey and the claims below
    // about format handling cannot be reached -- so the claim is that nothing
    // gets through, which is the whole of what this module promises until
    // somebody pins a signer.
    if !have_key() {
        claim(
            "no update key is provisioned, so every image is refused",
            verify(image, &[]) == Verdict::NoKey
                && verify(image, &[0u8; SIG_LEN]) == Verdict::NoKey,
        );
        kprintln!("       'python tools/sign.py --keygen' and paste into UPDATE_KEY to enable");
        return ok;
    }

    claim("an empty signature is refused", verify(image, &[]) == Verdict::Malformed);
    claim(
        "a signature of the right length but wrong magic is refused",
        verify(image, &[0u8; SIG_LEN]) == Verdict::Malformed,
    );

    let mut wrong_version = [0u8; SIG_LEN];
    wrong_version[..8].copy_from_slice(MAGIC);
    wrong_version[8] = 2;
    claim(
        "a future format is refused rather than guessed at",
        verify(image, &wrong_version) == Verdict::Unsupported,
    );

    let mut zeros = [0u8; SIG_LEN];
    zeros[..8].copy_from_slice(MAGIC);
    zeros[8] = 1;
    claim(
        "a well-formed signature of zeroes is not a signature",
        verify(image, &zeros) == Verdict::Bad,
    );

    ok
}
